### ISSUE TITLE
Is RedStore still active?

### ISSUE THREAD

**Issue by 5yt45ytrfyhtryr** [njh/redstore#53]
Is it still developed and maintained?

**Comment by njh** [comment]
I am not actively developing RedStore but I will attempt to review and accept Pull Requests where I can. It was stable for basic usage and has good test coverage. RedStore was intended to be a small/personal instance for testing and experimenting with RDF, rather than being something to load/host large datasets in.

See also a similar question here:
http://lists.librdf.org/pipermail/redland-dev/2017-March/002764.html
